### PR TITLE
Mapdb demo

### PR DESCRIPTION
**Pull request by pjfanning**
I tried https://jankotek.gitbooks.io/mapdb/content/ instead of H2 MVMap but so far with file backed dbs, MVMap has better performance.

Mapdb does have off-heap memory option which could be a useful option.

### CODE REVIEW

**Comment by pjfanning** [comment]
@mirahbo - I did an experiment with another lib - mapdb - but it performs worse than H2 MVMap, even when I use mapdb's off heap memory option (called memoryDirectDB).

The test case is maybe not very real world but just tried it out of interest.

**Comment by mirahbo** [comment]
... but MapDB uses a RandomAccessFile too, [according to their documentation](https://jankotek.gitbooks.io/mapdb/content/performance/). I'm going to investigate a bit more.

**Comment by pjfanning** [comment]
Thanks for the detailed response. I'm just surprised existing libs are so slow. I'll try your list impl and if it shows better perf - it might be worth you releasing it as a standalone solution that poi-shared-strings can use - but many other users might use it for other uses.

Sent from Yahoo Mail on Android 
 
  On Tue, 14 Dec 2021 at 16:11, Henry ***@***.***> wrote:   


... but MapDB uses a RandomAccessFile too, according to their documentation. I'm going to investigate a bit more.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pjfanning** [comment]
The in-built POI SharedStringTable is very fast because everything is in memory - maybe 1 million shared strings will not be that big - if you can afford to allow a big heap.

**Comment by mirahbo** [comment]
That's a good suggestion, thanks. However, our application processes files that are imported by our users. There might be even more than 1 million shared string in some files. It's hard to foresee how much memory the processing of a file can use. This is the reason why we need to  limit the usage of the memory, which we cannot do with the built-in POI SharedStringTable.

I was surprised too that querying the H2 key-value store uses that much CPU. Feel free to compare the profiling of your fork with monitorjbl's implementation when processing huge files if you're interested in this issue (even if there are more features in your fork).

I'm currently reworking my own PR. It currently doesn't meet the requirements of the automated tests. I think using caffeine is a good idea too, it works well for the cache.

**Comment by mirahbo** [comment]
@pjfanning I think that I found why there is such a difference between the implementations. This is because of the serialisation and the deserialisation of the CTRst objects in the H2 key value datastore. It consumes too much CPU time.

I have just tested replacing the CTRst objects by their .toString() representation (MVMap<Integer, String> instead of MVMap<Integer, CTRst>). Now, processing  my 1 million rows file takes 35s and the org.h2.mvstore.MVMap.get is not a CPU hot spot anymore.

This is the difference between's yours and monitorjbl's implementation: the later only store Strings, there is not any serialisation / deserialisation of a huge java object.

**Comment by pjfanning** [comment]
I only changed to storing CTRst recently - to support full format - wasn't aware it would cause such a perf impact

Let me see about supporting storing just plain strings when full format=false

**Pull request closed without merging**
